# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.CharField(max_length=1000)),
                ('metaphor_text', models.CharField(max_length=1000)),
                ('req_date', models.DateTimeField(verbose_name=b'date requested')),
                ('remote_addr', models.CharField(max_length=100)),
            ],
        ),
    ]
