# Generated by Django 2.0.2 on 2018-03-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphor', '0003_auto_20180205_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metaphor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.CharField(max_length=1000)),
                ('metaphor_text', models.CharField(max_length=1000)),
                ('strategy', models.CharField(max_length=1000)),
                ('req_date', models.DateTimeField(verbose_name='date requested')),
                ('remote_addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
