# Generated by Django 2.0.2 on 2018-03-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphor', '0004_auto_20180315_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaphor',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaphor',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
