# Generated by Django 2.0.2 on 2018-03-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaphor', '0005_auto_20180315_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaphor',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
